name: C/C++ CI

on:
  push:
    branches: [ main ]

jobs:
  ci:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04, ubuntu-22.04, macos-11, macos-12]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - name: test sudo
      run: </dev/null sudo -S -u nobody id
